### ISSUE TITLE
!announce <message>

### ISSUE THREAD

**Issue by tommyshelby9121** [VTPDevelopment/Silk#41]
Sends a message by the bot in the form of an embed (or not), includes everything added in `<message>` and mentions `@everyone` in a pre-determined channel which can be configurable.

**Comment by VelvetToroyashi** [comment]
This will be added as a plugin, very soon. 👀

**Comment by VelvetToroyashi** [comment]
I attempted to write a plugin for this, but re-evaluated the viability of this, and don't believe there's much of a use for it in a bot like Silk.
